export const defaultSiteContent = {
  schemaVersion: 1,
  global: {
    email: 'zetajie02@163.com',
    phone: '+86 181 2408 9092',
    logoPath: '/assets/zet-logo-128.png',
    contactCtaLabel: "Let's Talk",
    mobileRoleLines: ['UI/UX Designer', 'Product Manager'],
    mobileLocationLines: ['Shenzhen', 'China'],
    navItems: [
      { id: 'nav-home', label: 'Home', href: '#top' },
      { id: 'nav-projects', label: 'Projects', href: '#work' },
      { id: 'nav-profile', label: 'Profile', href: '#about' },
      { id: 'nav-contact', label: 'Reach Me', href: '#contact' },
    ],
  },

  opening: {
    metaLeft: 'ZET — PORTFOLIO',
    metaRight: 'SHENZHEN / 2026',
    word: 'FORM / FUNCTION',
    footerLeft: 'DESIGNING CLARITY',
    footerRight: '00—100',
  },

  hero: {
    videoUrl:
      'https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260622_204221_5339e40b-e73d-4ab0-9c65-79c18c66fd50.mp4',
    videoDesktopUrl: '/assets/hero-fish-desktop.mp4',
    videoMobileUrl: '/assets/hero-fish-mobile.mp4',
    poster: '/assets/hero-fish-poster.jpg',
    kicker: 'UI/UX DESIGNER · PRODUCT MANAGER',
    titleLines: ['把复杂问题，', '设计成清晰、好用、', '真正能落地的产品。'],
    support: '从产品策略、体验架构到界面设计，我专注医疗健康、智能硬件与复杂 B 端系统，让设计连接用户、业务与真实交付。',
    ctaLabel: '查看精选项目',
    ctaHref: '#work',
    metaItems: [
      { id: 'hero-meta-intro', label: '01 / INTRO', value: 'ZET PORTFOLIO' },
      { id: 'hero-meta-role', label: 'ROLE', value: 'UI/UX × PRODUCT' },
      { id: 'hero-meta-experience', label: 'EXPERIENCE', value: '11 YEARS · 7 IN UI/UX' },
      { id: 'hero-meta-base', label: 'BASE', value: 'SHENZHEN / CN' },
    ],
  },

  work: {
    index: '02',
    label: 'SELECTED WORK',
    title: '精选项目',
    intro: '这里不仅展示画面，也保留每个项目背后的产品判断、设计路径与真实结果。',
    carouselInstructions: '项目可横向浏览。使用鼠标拖拽、触控板或键盘左右方向键移动，聚焦卡片时自动滚动会暂停。',
    caseLabel: 'CASE',
    decisionLabel: '产品判断',
    resultLabel: '项目结果',
    viewLabel: '查看项目',
    placeholderViewLabel: '查看占位内容',
    pendingLabel: 'CASE IN PREPARATION',
    coverLabel: '项目封面',
    galleryLabel: '项目图片',
    editProjectLabel: '编辑项目内容',
    projects: [
      {
        id: 'changqing',
        number: '01',
        title: '长卿健康家园 V3.0',
        type: 'AI 医疗 · 小程序 · 适老化',
        role: 'Lead UI/UX',
        period: '2025',
        image: '/assets/project-changqing.webp',
        thumbnail: '/assets/project-changqing-card.jpg',
        imageAlt: '长卿健康家园 V3.0 多个核心界面展示',
        imageFit: 'contain',
        imageBackground: '#e9ecef',
        placeholder: false,
        summary:
          '面向家庭健康与慢病管理场景，重构产品功能结构、信息结构与核心界面，让健康检测、咨询和方案执行形成更清晰的闭环。',
        decision:
          '把 AI 入口放在健康概览和异常指标之后，让用户先理解问题，再通过自然语言或语音继续咨询。针对中老年用户加强字号、对比度、反馈和操作路径。',
        result: '主导 V3.0 产品重构，完成 AI-UX 对话体验与适老化界面设计。',
        tags: ['信息架构', 'AI-UX', '适老化', '设计规范'],
        gallery: [],
      },
      {
        id: 'unique-health',
        number: '02',
        title: 'Unique Health',
        type: '智能硬件 · 健康管理 · 0→1',
        role: 'PM & UI',
        period: '2023—2024',
        image: '/assets/project-unique-health.webp',
        thumbnail: '/assets/project-unique-health-card.jpg',
        imageAlt: 'Unique Health 产品流程与交互方案',
        imageFit: 'contain',
        imageBackground: '#e9ecef',
        placeholder: false,
        summary:
          '连接智能体脂秤等硬件，为用户提供实时健康数据监测、趋势分析和饮食管理。负责从需求研究到发布验收的完整产品过程。',
        decision:
          '以“记录状态—理解数据—制定目标”为主线收敛功能，并通过组件规范统一健康指标、趋势图和异常状态的表达。',
        result: '上线 6 个月内，间接促成 B 端业务销售额增长 20% 以上。',
        tags: ['0→1', '智能硬件', '产品规划', '组件库'],
        gallery: [],
      },
      {
        id: 'calorie',
        number: '03',
        title: '热量减肥法',
        type: '健康管理 · 数据驱动 · APP',
        role: 'UI/UX',
        period: '2021—2023',
        image: '/assets/project-calorie.webp',
        thumbnail: '/assets/project-calorie-card.jpg',
        imageAlt: '热量减肥法 APP 改版后的多个关键界面',
        imageFit: 'contain',
        imageBackground: '#e9ecef',
        placeholder: false,
        summary:
          '围绕热量记录、体重管理和饮食计划持续迭代 APP，同时规划后台的数据、内容、课程、会员与运营模块。',
        decision:
          '首页从信息堆叠转为任务分层，将热量余额、饮食记录与减脂计划提升为主路径，把趋势、运动和习惯移到次级层。',
        result: '负责项目期间新增用户 200 万，年增长率 70%，应用市场排名提升近 50%。',
        tags: ['首页改版', 'AARRR', '后台系统', '增长体验'],
        gallery: [],
      },
      {
        id: 'dashboard',
        number: '04',
        title: '企业数据可视化大屏',
        type: 'B 端 · 数据可视化 · 决策支持',
        role: 'Lead Designer',
        period: '2023',
        image: '/assets/project-dashboard.webp',
        thumbnail: '/assets/project-dashboard-card.jpg',
        imageAlt: '企业用户数据与用户画像可视化大屏',
        imageFit: 'contain',
        imageBackground: '#05101a',
        placeholder: false,
        summary:
          '面向企业管理层建立业务数据总览，用统一的指标层级呈现会员、增长、购买与用户画像，辅助快速理解经营状态。',
        decision:
          '先明确管理层的关键问题，再组织指标与图表；通过高层摘要、趋势与分群的层级关系减少“有数据、无结论”的大屏。',
        result: '主导规划与视觉设计，组织敏捷小组快速完成数据大屏 Demo。',
        tags: ['指标体系', '可视化', '敏捷协作', '管理驾驶舱'],
        gallery: [],
      },
      {
        id: 'odm',
        number: '05',
        title: 'ODM / OEM 定制产品体系',
        type: 'B 端服务 · 智能硬件 · 多品牌',
        role: 'PM & UI',
        period: '2021—2024',
        image: '/assets/project-odm.webp',
        thumbnail: '/assets/project-odm-card.jpg',
        imageAlt: 'ODM 与 OEM 多品牌健康应用图标展示',
        imageFit: 'contain',
        imageBackground: '#e9ecef',
        placeholder: false,
        summary:
          '为境内外智能硬件品牌提供分级软件定制服务，覆盖需求分析、产品架构、原型、UI、评审、验收和上线资料。',
        decision:
          '把高频沟通内容沉淀为对接文档、模板和标准流程，让不同定制等级保持清晰边界，降低跨团队交付中的信息损耗。',
        result: '完成 20+ 家企业定制对接，服务小米、荣耀、OPPO、Anker、松下等品牌。',
        tags: ['B 端沟通', '需求管理', '交付规范', '跨品牌设计'],
        gallery: [],
      },
      {
        id: 'research-platform',
        number: '06',
        title: '长卿科研平台',
        type: '科研数据 · B 端平台 · 医疗健康',
        role: 'Case in preparation',
        period: 'COMING SOON',
        image: '/assets/project-research.webp',
        thumbnail: '/assets/project-research-card.jpg',
        imageAlt: '长卿科研平台界面展示',
        imageFit: 'cover',
        imageBackground: '#121418',
        placeholder: true,
        summary: '项目素材已经收录，完整的项目背景、设计过程与交付说明正在整理中。',
        decision: '待补充完整的业务目标、信息架构与关键设计判断。',
        result: '案例整理中，后续将补充可公开的项目结果。',
        tags: ['案例整理中', '科研数据', 'B 端平台'],
        gallery: [],
      },
      {
        id: 'body-composition',
        number: '07',
        title: '智能体测终端',
        type: '智能硬件 · 触控终端 · 健康报告',
        role: 'Case in preparation',
        period: 'COMING SOON',
        image: '/assets/project-body-screen.webp',
        thumbnail: '/assets/project-body-screen-card.jpg',
        imageAlt: '智能体测终端界面展示',
        imageFit: 'cover',
        imageBackground: '#121418',
        placeholder: true,
        summary: '界面视觉与核心流程已经收录，完整案例内容将在素材整理后补充。',
        decision: '待补充设备操作场景、测量流程与报告信息层级的设计说明。',
        result: '案例整理中，当前作为项目画廊的视觉占位。',
        tags: ['案例整理中', '智能硬件', '触控体验'],
        gallery: [],
      },
    ],
  },

  profile: {
    index: '03',
    label: 'PROFILE',
    title: '经历与方法',
    intro: '从界面表现走向产品结构，我更关心设计如何被理解、被使用，并真正进入业务。',
    portrait: {
      src: '/assets/portrait-zet-color-880.avif',
      alt: '郑龙杰，UI/UX 设计师与产品经理',
      name: 'ZHENG LONGJIE',
      location: 'SHENZHEN / CN',
    },
    leadLabel: 'UI DESIGNER · PRODUCT MANAGER',
    emailLabel: 'EMAIL',
    phoneLabel: 'PHONE',
    timelineTitle: '工作经历',
    timelineRange: '2015 — 现在',
    statementParts: [
      { id: 'profile-statement-prefix', text: '兼具 ' },
      { id: 'profile-statement-uiux', text: 'UI/UX 设计', accent: true },
      { id: 'profile-statement-connector', text: ' 与 ' },
      { id: 'profile-statement-product', text: '产品管理', accent: true },
      { id: 'profile-statement-suffix', text: ' 能力，能够从问题定义一路推进到设计落地。' },
    ],
    summary:
      '11 年工作经验，其中 7 年专注 UI/UX。项目覆盖医疗健康、智能硬件、电商、数据可视化与企业定制服务。擅长用户研究、产品规划、信息架构、交互与视觉设计，并持续将 AI 工具融入设计流程。',
    metrics: [
      { id: 'metric-uiux-years', value: '7+', label: '年 UI/UX 经验' },
      { id: 'metric-custom-clients', value: '20+', label: '家企业定制对接' },
      { id: 'metric-new-users', value: '200万', label: '项目新增用户' },
      { id: 'metric-known-brands', value: '5', label: '个知名品牌服务经验' },
    ],
    experience: [
      {
        id: 'experience-geekjump-2025',
        period: '2025.11 — NOW',
        company: '深圳极客跳动科技有限公司',
        role: 'UI设计&产品经理',
        note: '项目 UI、组件库与协作流程建设，并将 AI 工具融入设计工作流。',
      },
      {
        id: 'experience-aosa-2025',
        period: '2025.03 — 2025.11',
        company: '深圳奥萨医学信息技术有限公司',
        role: '高级 UI 设计师',
        note: '负责医疗健康小程序、H5、数据看板与智慧触控屏，主导长卿系列产品重构。',
      },
      {
        id: 'experience-lefu-2021',
        period: '2021.04 — 2024.06',
        company: '深圳市乐福衡器有限公司',
        role: 'PM & UI',
        note: '从 0 到 1 规划健康产品，交付 ODM/OEM 定制项目、后台系统与数据大屏。',
      },
      {
        id: 'experience-luoti-2020',
        period: '2020.04 — 2021.04',
        company: '深圳市络缇电子商务有限公司',
        role: 'UI/UX 设计师',
        note: '负责电商产品原型、交互、动效、视觉规范，并参与设计团队管理。',
      },
      {
        id: 'experience-mtr-2015',
        period: '2015.03 — 2020.03',
        company: '港铁轨道交通（深圳）有限公司',
        role: '技术员',
        note: '参与品牌视觉、官网、小程序与运营物料设计，积累跨部门协作经验。',
      },
    ],
  },

  capabilities: {
    index: '04',
    label: 'CAPABILITIES',
    title: '个人优势',
    intro: '设计能力用作品证明，协作能力用交付证明。',
    items: [
      {
        id: 'capability-product-strategy',
        number: '01',
        title: '产品策略',
        en: 'Product Strategy',
        copy: '从业务目标与用户问题出发，建立可执行的产品路径。',
        items: ['用户与竞品研究', '需求池与优先级', '产品架构与里程碑'],
        evidence: '主导 Unique Health 从 0 到 1',
      },
      {
        id: 'capability-ux-architecture',
        number: '02',
        title: '体验架构',
        en: 'UX Architecture',
        copy: '在复杂功能中厘清信息关系，让任务路径自然、稳定、可理解。',
        items: ['信息架构', '业务流程与原型', '多端与适老化体验'],
        evidence: '主导长卿 V3.0 结构与体验重构',
      },
      {
        id: 'capability-interface-craft',
        number: '03',
        title: '界面设计',
        en: 'Interface Craft',
        copy: '把品牌、内容与交互统一到完整的视觉系统中。',
        items: ['视觉语言与动效', '组件库与设计规范', '数据可视化'],
        evidence: '2022 年度「最具创新奖」',
      },
      {
        id: 'capability-delivery',
        number: '04',
        title: '项目落地',
        en: 'Delivery & Collaboration',
        copy: '连接客户、产品、研发、测试与运营，让方案按目标上线。',
        items: ['B 端需求沟通', '评审、走查与验收', 'AI 辅助设计工作流'],
        evidence: '20+ 家企业定制项目经验',
      },
    ],
  },

  contact: {
    displayLabel: 'REACH ME',
    kickerLabel: '05 / CONTACT',
    kickerLocation: 'SHENZHEN · CHINA',
    pretitle: '有复杂的问题，',
    title: '一起把它变清楚',
    copyLabel: '复制',
    copiedLabel: '已复制',
    links: [
      { id: 'contact-phone', label: '电话', href: 'tel:+8618124089092', external: false },
      {
        id: 'contact-zcool',
        label: '站酷',
        href: 'https://www.zcool.com.cn/work/ZNDc2MjYzMzI=.html',
        external: true,
      },
      {
        id: 'contact-yuque',
        label: '语雀',
        href: 'https://www.yuque.com/u12559102/kb/fvc44bg30b167ggf',
        external: true,
      },
    ],
    copyright: '© 2026 ZET. DESIGNED WITH CLARITY.',
  },
}

export default defaultSiteContent
